pipeline { 
  agent { 
    kubernetes { 
      label 'jenkins-agent-my-app' 
      serviceAccount 'jenkins'
      yaml """ 
apiVersion: v1 
kind: Pod 
metadata: 
  labels: 
    component: ci 
spec: 
  containers: 
    - name: python 
      image: python:3.7 
      command: 
        - cat 
      tty: true 
    - name: docker 
      image: docker 
      command: 
        - cat 
      tty: true 
      volumeMounts: 
        - mountPath: /var/run/docker.sock 
          name: docker-sock 
    - name: kubectl 
      image: lachlanevenson/k8s-kubectl:v1.17.2 
      command: 
        - cat 
      tty: true 
  volumes: 
    - name: docker-sock 
      hostPath: 
        path: /var/run/docker.sock 
""" 
    } 
  } 

  triggers { 
      pollSCM('* * * * *') 
  } 

  stages { 
    stage('Test python') { 
      steps { 
        container('python') { 
          dir('flask_app') {
            sh "pip install -r requirements.txt" 
            sh "python test.py" 
          }
        } 
      } 
    } 

    stage('Build image') { 
      steps { 
        container('docker') { 
          dir('flask_app') {
            withCredentials([usernamePassword(credentialsId: 'dockerhubcreds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
              sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
              sh "docker build -t ${DOCKER_USER}/pythontest:latest ." 
              sh "docker push ${DOCKER_USER}/pythontest:latest" 
            }
          }
        } 
      } 
    } 

    stage('Deploy') { 
      steps { 
        container('kubectl') { 
          dir('flask_app') {
            withCredentials([usernamePassword(credentialsId: 'dockerhubcreds', usernameVariable: 'DOCKER_USER', passwordVariable: '')]) {
              sh "sed -i 's|localhost:4000/pythontest:latest|docker.io/${DOCKER_USER}/pythontest:latest|g' ./kubernetes/deployment.yaml"
              sh "kubectl apply -f ./kubernetes/deployment.yaml" 
              sh "kubectl apply -f ./kubernetes/service.yaml" 
            }
          }
        } 
      } 
    } 
  } 
} 
