pipeline { 
  agent { 
    kubernetes { 
      label 'jenkins-agent-my-app' 
      serviceAccount 'jenkins'
      yaml """ 
apiVersion: v1 
kind: Pod 
metadata: 
  labels: 
    component: ci 
spec: 
  containers: 
    - name: python 
      image: python:3.7 
      command: 
        - cat 
      tty: true 
    - name: docker 
      image: docker 
      command: 
        - cat 
      tty: true 
      volumeMounts: 
        - mountPath: /var/run/docker.sock 
          name: docker-sock 
    - name: kubectl 
      image: lachlanevenson/k8s-kubectl:v1.17.2 
      command: 
        - cat 
      tty: true 
  volumes: 
    - name: docker-sock 
      hostPath: 
        path: /var/run/docker.sock 
""" 
    } 
  } 

  triggers { 
      pollSCM('* * * * *') 
  } 

  stages { 
    stage('Test python') { 
      steps { 
        container('python') { 
          dir('flask_app') {
            sh "pip install -r requirements.txt" 
            sh "python test.py" 
          }
        } 
      } 
    } 

    stage('Build image') { 
      steps { 
        container('docker') { 
          dir('flask_app') {
            sh "docker build -t gcr.io/project-f3cc5de9-ac6f-4df9-88a/pythontest:latest ." 
            sh "docker push gcr.io/project-f3cc5de9-ac6f-4df9-88a/pythontest:latest" 
          }
        } 
      } 
    } 

    stage('Deploy') { 
      steps { 
        container('kubectl') { 
          dir('flask_app') {
            sh "kubectl apply -f ./kubernetes/deployment.yaml" 
            sh "kubectl apply -f ./kubernetes/service.yaml" 
          }
        } 
      } 
    } 
  } 
} 
